### ISSUE TITLE
Direct debit group IBAN required

### ISSUE THREAD

**Issue by sigmike** [salesking/sepa_king#13]
A valid account (IBAN and BIC) is required on the SEPA::DirectDebit object, otherwise validation fails[[1]](https://github.com/ouvrages/sepa_king/blob/master/lib/sepa_king/message.rb#L16).

But since the creditor IBAN is only used at the transaction level, why is it required at the top level?

**Comment by ledermann** [comment]
To cleanup issues I'm closing this old one. Please tell me if there are still any problems.
