### ISSUE TITLE
Requested Date: Today should also be valid

### ISSUE THREAD

**Issue by tobischo** [salesking/sepa_king#18]
We are using sepa_king to generate SEPA Transfer files in order to tell our bank to transfer money to our customers.
We noticed that it sets the requested_date for CreditTransfers to the date after creation as default

The default seems ok - however, it is also not possible to pass in today as a date.

Is there a particular reason that it has to be the next day and today is specifically not allowed?
I couldn't find any documentation about it and our bank says setting the date to today is fine for them.
(We generate the files in the morning and give them to the bank to execute some time during the day)

**Comment by phillipp** [comment]
My bank doesn't accept the XML with ReqdExctnDt set to today (via HBCI) but is happy to accept the XML and executes the transfer on the same day when the ReqdExctnDt is set to *1999-01-1*, so I would appreciate if this magic value could be set. Can we go forward with this?

If yes: should I add a pull request or would you like to add it?

**Comment by ledermann** [comment]
@phillipp: While not described in the specification, it seems that 1999-01-01 is [allowed](https://www.bundesbank.de/Redaktion/DE/Downloads/Aufgaben/Unbarer_Zahlungsverkehr/technische_spezifikation_sepa_ueberweisungen_november_2014.pdf) for CreditTransfers to define same day execution, so a PR would be nice.

**Comment by phillipp** [comment]
I could find it in the specs of the Bundesbank and ZK (Zentraler Kreditausschuss (https://www.bundesbank.de/Redaktion/DE/Downloads/Aufgaben/Unbarer_Zahlungsverkehr/verfahrensregeln_sepa_ueberweisungen_november_2014.pdf?__blob=publicationFile and https://www.hbci-zka.de/dokumente/aenderungen/V3.0/GV_SEPA_Uebertrag.pdf), both say that the field MUST be 1999-01-01.

The spec 2.2 of the Bundesbank says the the ReqdExctnDt should be used as "entweder mit dem Standardwert „1999-01-01“ oder dem
Buchungstag des jeweiligen Einlieferungsfensters (für das 1. Einlieferungsfenster der aktuelle
Geschäftstag und für das 2. Einlieferungsfenster der nächste Geschäftstag) zu belegen. "

As you normally don't want to calculate which window you are about to hit with your XML you would normally want the bank to execute the transfer "on sight" (Überweisung auf Sicht).

Another guide of the VR banking group (https://www.dkm.de/content/dam/webbankplus/downloads/checklisten-wissen/sepa-leitfaden-firmenkunden.pdf) says that all credit transfers with ReqdExctnDt "1999-01-01" are "bei Sicht fällige Überweisungen" (credits to be transferred on sight).

So I would actually want to propose the bold move to make 1999-01-01 the default. I can understand that this *may* break compatibility but I think the cance is very small as there are quite a lot of specs and documents that talk about that magic value from a lot of major and minor banks.

Would that be acceptable? I would then craft a pull request.

**Comment by ledermann** [comment]
@phillipp Thanks for you detailed proposal. I agree to make `1999-01-01` as default for `<ReqdExctnDt>` (for CreditTransfer, not DirectDebit). I'm looking forward to your Pull Request.

**Comment by phillipp** [comment]
Looks like merging #49 finished this too, right (because the default is now for the bank to execute the credit transfer ASAP)?

**Comment by ledermann** [comment]
Yes, I think so too.
