### ISSUE TITLE
Id in InitgPty tag

### ISSUE THREAD

**Issue by vevisystems** [salesking/sepa_king#38]
Spanish banks seem to require an Id tag inside the InitiatingParty (InitgPty) tag, not just a name. Something like:

  &lt;CstmrDrctDbtInitn&gt;
    &lt;GrpHdr&gt;
      ...
      &lt;InitgPty&gt;
        &lt;Nm&gt;COMPNAY NAME&lt;/Nm&gt;
        &lt;Id&gt;
          &lt;OrgId&gt;
            &lt;Othr&gt;
              &lt;Id&gt;XXXXXXXXXXXXXX&lt;/Id&gt;
            &lt;/Othr&gt;
          &lt;/OrgId&gt;
        &lt;/Id&gt;
      &lt;/InitgPty&gt;
    &lt;/GrpHdr&gt;

How can this be done? It seems it is not supported, isn't? Could you please add support for this?

In any case, thank you for this gem!

**Comment by dolarsrg** [comment]
Fixed at https://github.com/salesking/sepa_king/pull/40

**Comment by ledermann** [comment]
Closed by #44
