### ISSUE TITLE
Exposing detailed errors

### ISSUE THREAD

**Issue by namxam** [salesking/sepa_king#45]
Before submitting a pull request, I just want to check if you are open for this change. Message#add_transaction raises an ArgumentError exception when attributes have invalid data. But it only exposes them via a single error message. In our case, we would like to have them in a format like `{ bic: ['is invalid'] }`. In general one can attach additional data to exceptions, which in this case would be quite useful.

**Comment by ledermann** [comment]
I like this idea, a PR would be very appreciated.

**Comment by namxam** [comment]
Thank you for your feedback. I will have a look at it and submit one.
