### ISSUE TITLE
Ability to set a custom CreDtTm

### ISSUE THREAD

**Issue by vzamanillo** [salesking/sepa_king#63]
Hi!

In my case, the produced value for CreDtTm (Time.now.iso8601) includes a numeric time offset (the host date is set to CET, `vie ene 20 13:37:31 CET 2017`)

`<CreDtTm>2017-01-20T12:06:07+00:00</CreDtTm>`

and is not considered as a valid value for some Spanish banks (Liberbank in this case), it should be great the possibility to using a custom date.

I think fixed on PR #59.

**Comment by ledermann** [comment]
Fixed by #76
