### ISSUE TITLE
Plans to support SEPA 3.1

### ISSUE THREAD

**Issue by jdrees** [salesking/sepa_king#67]
I really like your gem. Thank you for putting in the effort!
My question is, are there any plans to support the updated specifications of SEPA 3.1?
As far as I can tell, this library is still based around the 2.7 version vom late 2013 and some things have changed over the past few years like removing the COR1 option and no longer differentiating between first, last and recurring transactions.

**Comment by ledermann** [comment]
Currently there are no plans for this, but we are open for PR. Adding support for latest specification would be a great enhancement.

**Comment by magegu** [comment]
Yes, we'll need to look into it, too. First SEPA::CreditTransfer's are bouncing for us from CH.

Our Bank just explained why:
„Die Zahlungspflichtigen-Adresse bei Lastschrifteinreichung ist Pflicht bei Lastschriften außerhalb der EU/EWR (Geldtransferverordnung (EU) 2015/847). Das betrifft derzeit folgende Länder: Schweiz (CH), Monaco (MC), San Marino (SM), Jersey (JE), Guernsey (GG), Isle of Man (IM), St. Pierre und Miquelon (PM) sowie – je nach Brexit-Vereinbarung – auch zukünftig Großbritannien (GB).“

Beispiel:
<Nm>XYZ Beispiel GmbH</Nm>
<PstlAdr>
<Ctry>DE</Ctry>
<AdrLine>Stadtgasse 3</AdrLine>
<AdrLine>Berlin</AdrLine>
</PstlAdr>

I might prepare a PR soonish. Not sure when I'll find the time :(

**Comment by chrisokamoto** [comment]
Any update on this?

**Comment by magegu** [comment]
linking my PR #71 for this feature
