### ISSUE TITLE
Parsing/storing documents

### ISSUE THREAD

**Issue by grncdr** [salesking/sepa_king#75]
Hi, thanks for the library, it's been a huge help!

Is there a recommended way to _de_-serialize the documents created by e.g. `Sepa::CreditTransfer.new(...).to_xml`? I'm currently storing a log of all the XML docs we submit, and getting data out of them later means a lot of Xpath. It would be great if there was some sort of `from_xml` method that would give me an object equivalent to the one I called `to_xml` on.

Use cases for me include test assertions and displaying useful details about what bank transactions we've initiated with a given document.

**Comment by MrTin** [comment]
Wouldn't it be better to just store the input in a format you prefer alongside storing the generated output instead of trying to use the XML as a serializer?

**Comment by grncdr** [comment]
Hey, sorry I don't really remember what I was trying to accomplish when I opened this issue, but clearly it hasn't been a show-stopper. I think it's safe to close it.
