### ISSUE TITLE
Support Swiss Payment Standards

### ISSUE THREAD

**Issue by tobischo** [salesking/sepa_king#81]
Switzerland uses pain.001 and pain.008 Formats that are derived from the official SEPA standard.
These formats are defined by the SIX Group (https://www.six-group.com/interbank-clearing/de/home/standardization/iso-payments/customer-bank/implementation-guidelines.html).

While Swiss Payment Standards (SPS) are very similar to SEPA, they technically aren't part of it.
In order to support it regardless, the following formats would have to be supported:
* `pain.008.001.02.ch.03` ([Implementation Guidline (pdf)](https://www.six-group.com/interbank-clearing/dam/downloads/de/standardization/iso/swiss-recommendations/implementation-guidelines-swiss-dd.pdf), [Schema and examples (zip)](https://www.six-group.com/interbank-clearing/dam/downloads/en/standardization/iso/swiss-recommendations/implementation-guidelines-swiss-dd-examples.zip))
* `pain.001.001.03.ch.02` ([Implementation Guidline (pdf)](https://www.six-group.com/interbank-clearing/dam/downloads/de/standardization/iso/swiss-recommendations/implementation-guidelines-ct.pdf), [Schema and examples (zip)](https://www.six-group.com/interbank-clearing/dam/downloads/en/standardization/iso/swiss-recommendations/implementation-guidelines-ct-examples.zip))

Would you be willing to accept a PR that adds support for it? (even though it is technically not SEPA)

**Comment by ledermann** [comment]
Yes, a PR would be fine.

**Comment by tobischo** [comment]
Great :-) I will try to get a PR ready soon

**Comment by tobischo** [comment]
I have looked into this some more and I came across the following:
There are a number of differences, especially for debits:

Credit Transfers [1]:
* can be used almost identical, the difference is mostly the XML namespace

Direct Debits [2] for [LSV+](https://www.lsv.ch/dam/downloads/en/fi/d0342-03-dd-handbook-for-billers-en.pdf):
* Uses Clearing System Member ID instead of BIC [2] p.22
** I think that is the swiss bank code and could be automatically retrieved from the IBAN, but I am not 100% certain of that and couldn't get a confirmation for that yet
* If ISR Debits are used, you need to provide the ISR Participant Number [2] p.23
* It uses structured remittance information to pass along ISR or IPI reference numbers
* It does NOT use mandate_id and mandate_date_of_signature
* service_level is either CHDD or CHTA
* local_instrument depends on service level and is DDCOR1, DDB2B, LSV+ and BDD
* sequence_type is not used
* batch_booking is not used

That seems like quite a lot of differences, although some being rather minor.
My current approach is to add swiss direct debits into the existing `SEPA:DirectDebit` class

I am not entirely sure whether this is the best approach though.
Alternative I could think of
1. create a separate class for swiss direct debits within the SEPA namespace
2. create a separate class for swiss direct debits in a new namespace (e.g. SPS)
3. create an entirely separate gem which is similar to sepa_king (e.g. sps_king, maintained by [Barzahlen](https://github.com/Barzahlen))

What do you think?

[1] https://www.six-group.com/interbank-clearing/dam/downloads/de/standardization/iso/swiss-recommendations/implementation-guidelines-ct.pdf 
[2] https://www.six-group.com/interbank-clearing/dam/downloads/de/standardization/iso/swiss-recommendations/implementation-guidelines-swiss-dd.pdf

**Comment by tobischo** [comment]
Closed as per discussion on #82 

We will create a separate gem that handles this which will probably look very similar to sepa_king.
